/* Pre-saved contact directory for The Riverside Practice (Dr Rajiv Goel),
   Theydon Road Health Centre, Upper Clapton, London E5 — the hospitals,
   departments and pharmacies its staff dial most, powering the instant
   lookup on the library page. Numbers from the practice site, homerton.nhs.uk,
   bartshealth.nhs.uk and nhs.uk (checked July 2026). */

export const LOOKUP_CATEGORIES = ['All', 'Hospital', 'Department', 'Pharmacy', 'Practice', 'Urgent'];

export const DIRECTORY = [
  /* ---- the practice itself ---- */
  {
    id: 'riverside-reception',
    name: 'Riverside Practice — Reception',
    category: 'Practice',
    phone: '020 8806 1928',
    where: 'Theydon Road Health Centre, 14 Urban Hive, London E5 9BQ',
    note: 'Appointments, prescriptions, test results',
    keywords: ['dr goel', 'front desk', 'surgery', 'gp', 'main line'],
  },
  {
    id: 'riverside-phlebotomy',
    name: 'Phlebotomy Clinic (via reception)',
    category: 'Practice',
    phone: '020 8806 1928',
    where: 'Riverside Practice, E5 9BQ',
    note: 'Blood tests — book through reception',
    keywords: ['blood test', 'bloods', 'samples'],
  },
  {
    id: 'riverside-asthma',
    name: 'Asthma Clinic (via reception)',
    category: 'Practice',
    phone: '020 8806 1928',
    where: 'Riverside Practice, E5 9BQ',
    note: 'Respiratory reviews and inhaler checks',
    keywords: ['respiratory', 'inhaler', 'copd'],
  },
  {
    id: 'riverside-smoking',
    name: 'Smoking Cessation Clinic (via reception)',
    category: 'Practice',
    phone: '020 8806 1928',
    where: 'Riverside Practice, E5 9BQ',
    note: 'Stop-smoking support',
    keywords: ['quit smoking', 'nicotine', 'stop smoking'],
  },
  {
    id: 'riverside-obesity',
    name: 'Obesity Management Clinic (via reception)',
    category: 'Practice',
    phone: '020 8806 1928',
    where: 'Riverside Practice, E5 9BQ',
    note: 'Weight management support',
    keywords: ['weight', 'diet', 'nutrition'],
  },
  {
    id: 'riverside-counselling',
    name: 'Primary Care Counselling (via reception)',
    category: 'Practice',
    phone: '020 8806 1928',
    where: 'Riverside Practice, E5 9BQ',
    note: 'Talking therapy referrals',
    keywords: ['mental health', 'therapy', 'talking'],
  },

  /* ---- hospitals ---- */
  {
    id: 'homerton',
    name: 'Homerton University Hospital',
    category: 'Hospital',
    phone: '020 8510 5555',
    where: 'Homerton Row, London E9 6SR',
    note: 'Main local acute hospital & A&E for Hackney — switchboard',
    keywords: ['switchboard', 'a&e', 'accident emergency', 'casualty', 'hackney'],
    boost: 2, // ties with its own departments should resolve to the switchboard
  },
  {
    id: 'royal-london',
    name: 'The Royal London Hospital',
    category: 'Hospital',
    phone: '020 7377 7000',
    where: 'Whitechapel Road, London E1 1FR',
    note: 'Barts Health — major trauma centre, A&E, children’s A&E',
    keywords: ['barts', 'whitechapel', 'trauma', 'paediatrics'],
  },
  {
    id: 'st-barts',
    name: 'St Bartholomew’s Hospital',
    category: 'Hospital',
    phone: '020 7377 7000',
    where: 'West Smithfield, London EC1A 7BE',
    note: 'Barts Health — specialist cardiac & cancer centre (no A&E)',
    keywords: ['barts', 'cardiology', 'heart', 'cancer', 'oncology'],
  },
  {
    id: 'whipps-cross',
    name: 'Whipps Cross University Hospital',
    category: 'Hospital',
    phone: '020 8539 5522',
    where: 'Whipps Cross Road, Leytonstone E11 1NR',
    note: 'Barts Health — A&E and maternity',
    keywords: ['leytonstone', 'maternity'],
  },
  {
    id: 'newham',
    name: 'Newham University Hospital',
    category: 'Hospital',
    phone: '020 7476 4000',
    where: 'Glen Road, Plaistow E13 8SL',
    note: 'Barts Health — A&E',
    keywords: ['plaistow'],
  },
  {
    id: 'mile-end',
    name: 'Mile End Hospital',
    category: 'Hospital',
    phone: '020 7377 7000',
    where: 'Bancroft Road, London E1 4DG',
    note: 'Barts Health — community, outpatient & rehab services',
    keywords: ['outpatients', 'rehabilitation'],
  },
  {
    id: 'moorfields',
    name: 'Moorfields Eye Hospital',
    category: 'Hospital',
    phone: '020 7253 3411',
    where: '162 City Road, London EC1V 2PD',
    note: 'Specialist eye hospital — urgent eye care',
    keywords: ['eye', 'ophthalmology', 'vision', 'sight'],
  },
  {
    id: 'st-josephs',
    name: 'St Joseph’s Hospice',
    category: 'Hospital',
    phone: '020 8525 6000',
    where: 'Mare Street, Hackney E8 4SA',
    note: 'Palliative & end-of-life care',
    keywords: ['palliative', 'end of life', 'hospice'],
  },

  /* ---- hospital departments ---- */
  {
    id: 'homerton-appointments',
    name: 'Homerton Appointments Centre',
    category: 'Department',
    phone: '020 8510 5544',
    where: 'Homerton University Hospital',
    note: 'Outpatient bookings — Mon–Fri 8am–8pm',
    keywords: ['outpatients', 'booking', 'referral', 'clinic'],
  },
  {
    id: 'homerton-pals',
    name: 'Homerton PALS',
    category: 'Department',
    phone: '020 8510 7315',
    where: 'Homerton University Hospital',
    note: 'Patient Advice & Liaison — Mon–Fri 9am–5pm',
    keywords: ['complaints', 'patient advice', 'liaison'],
  },
  {
    id: 'homerton-records',
    name: 'Homerton Medical Records',
    category: 'Department',
    phone: '020 8510 7008',
    where: 'Homerton University Hospital',
    note: 'Copies of notes, discharge summaries',
    keywords: ['notes', 'discharge', 'records'],
  },

  /* ---- pharmacies ---- */
  {
    id: 'hackney-pharmacy',
    name: 'Hackney Pharmacy',
    category: 'Pharmacy',
    phone: '020 8806 6215',
    where: '15A Urban Hive, Theydon Road E5 9BQ',
    note: 'Next door to the practice — Mon–Fri 9–7, Sat 11–4',
    keywords: ['chemist', 'prescription', 'dispensary', 'next door'],
  },
  {
    id: 'asvacare-pharmacy',
    name: 'Asvacare Pharmacy',
    category: 'Pharmacy',
    phone: '020 8806 5140',
    where: '97 Upper Clapton Road, London E5 9BU',
    note: 'Community pharmacy on Upper Clapton Road',
    keywords: ['chemist', 'prescription', 'dispensary', 'clapton'],
  },

  /* ---- urgent ---- */
  {
    id: 'emergency-999',
    name: 'Emergency — Ambulance / Police / Fire',
    category: 'Urgent',
    phone: '999',
    where: 'National',
    note: 'Life-threatening emergencies only',
    keywords: ['ambulance', 'emergency', 'urgent', 'life threatening'],
  },
  {
    id: 'nhs-111',
    name: 'NHS 111',
    category: 'Urgent',
    phone: '111',
    where: 'National, 24/7',
    note: 'Urgent medical advice when it’s not a 999 emergency',
    keywords: ['out of hours', 'advice', 'urgent care'],
  },
  {
    id: 'crisis-line',
    name: 'City & Hackney Mental Health Crisis Line',
    category: 'Urgent',
    phone: '0800 073 0006',
    where: 'East London NHS Foundation Trust, 24/7',
    note: 'Freephone mental health crisis support',
    keywords: ['crisis', 'mental health', 'elft', 'psychiatric'],
  },
];
